ClinkDev:
  #########################################################################################################
  ClinkFeb[:]:
    ###################
    ClinkTop:
    ###################
      ###################
      ChannelA:
        enable: True
        LinkMode: Base
        DataMode: 12Bit
        FrameMode: Frame
        TapCount: 10
        DataEn: True
        BaudRate: 57600 
        SwControlValue: 0x0
        SwControlEn: 0x0
      ###################
      ChannelB:
        enable: True
        LinkMode: Base
        DataMode: 12Bit
        FrameMode: Frame
        TapCount: 10
        DataEn: True
        BaudRate: 57600
        SwControlValue: 0x0
        SwControlEn: 0x0
    ###################
    TrigCtrl[0]:
      EnableTrig: True
      InvCC: False
      TrigMap: ChA
      TrigPulseWidth: 0xfff
      TrigMask: 0x1
    ###################
    TrigCtrl[1]:
      EnableTrig: True
      InvCC: False
      TrigMap: ChB
      TrigPulseWidth: 0xfff
      TrigMask: 0x1
    ###################
    BoardTemp:
      RemoteTcritSetpoint: 100 # Prevent FEB from thermal shutdown until FPGA Tj = 100 degC (max. operating temp)
  #########################################################################################################
  Application:
    AppLane[0:4]: # Apply the configurations to 0 through 3
      EventBuilder:
        Timeout: 781250 # (156.25 MHz) x 5 ms = 781,250  
  #########################################################################################################
  Hardware:
    Timing:
      ###################
      TimingDbgMon:
        Loopback: 0x0
        # UseMiniTpg: False
        UseMiniTpg: True # True for standalone testing
      ###################
      Triggering: # https://confluence.slac.stanford.edu/download/attachments/216713616/ConfigEvrV2CoreTriggersYaml.pdf
        ###################
        Ch[:]: # [:] is a wildcard for all devices
          EnableReg: True
          RateSel: 0x1028
          DestSel: 0x20000
        ###################
        LocalTrig[:]: # [:] is a wildcard for all devices
          EnableTrig: True
          Polarity: Rising
          Delay: 0x0
          Width: 0x1 # 0x1 = one cycle pulse
        LocalTrig[0]:
          Source: 0x0 # CH0
        LocalTrig[1]:
          Source: 0x1 # CH1
        LocalTrig[2]:
          Source: 0x2 # CH2
        LocalTrig[3]:
          Source: 0x3 # CH3  
        ###################
        RemoteTrig[:]: # [:] is a wildcard for all devices
          EnableTrig: True
          Polarity: Rising
          Delay: 0x0
          Width: 0x1 # 0x1 = one cycle pulse
        RemoteTrig[0]:
          Source: 0x0 # CH0
        RemoteTrig[1]:
          Source: 0x1 # CH1
        RemoteTrig[2]:
          Source: 0x2 # CH2
        RemoteTrig[3]:
          Source: 0x3 # CH3            
      ###################
      TimingFrameRx:
        ClkSel: 0x0 # 0x0 = LCLS-I timing
        RxDown: 0x0 # Reset the latching register
      ###################
      