ClinkDevRoot:
  enable: True
  ClinkPcie:
    enable: True
    Application:
      enable: True
      AppLane[:]:
        enable: True
        EventBuilder:
          enable: True
          Bypass: 0x0
          Timeout: 0x0
          Blowoff: True
    Hsio:
      enable: True
      TimingRx:
        enable: True
        TimingFrameRx:
          enable: True
          ClkSel: LCLS-I Clock
          ModeSel: Lcls1Protocol
          ModeSelEn: UseClkSel
        TriggerEventManager:
          enable: True
          EvrV2CoreTriggers:
            enable: True
            EvrV2ChannelReg[0]:
              enable: True
              EnableReg: True
              RateType: ControlWord
              RateSel: 0x28
              DestType: All
              DestSel: 0x0
            EvrV2TriggerReg[0]:
              enable: True
              EnableTrig: True
              Source: 0x0
              Polarity: Rising
              ComplEn: Disabled
              ComplAnd: LogicOR
              Delay: 0x0
              Width: 0x1
          TriggerEventBuffer[0]:
            enable: True
            MasterEnable: True
            PauseThreshold: 16
            TriggerDelay: 42
        TimingPhyMonitor:
          enable: True
          Loopback: 'No'
          UseMiniTpg: True
